#pragma once

#define AR_MOUSE_BUTTON_1         0
#define AR_MOUSE_BUTTON_2         1
#define AR_MOUSE_BUTTON_3         2
#define AR_MOUSE_BUTTON_4         3
#define AR_MOUSE_BUTTON_5         4
#define AR_MOUSE_BUTTON_6         5
#define AR_MOUSE_BUTTON_7         6
#define AR_MOUSE_BUTTON_8         7
#define AR_MOUSE_BUTTON_LAST      AR_MOUSE_BUTTON_8
#define AR_MOUSE_BUTTON_LEFT      AR_MOUSE_BUTTON_1
#define AR_MOUSE_BUTTON_RIGHT     AR_MOUSE_BUTTON_2
#define AR_MOUSE_BUTTON_MIDDLE    AR_MOUSE_BUTTON_3
enum MouseCode
{
	MOUSE_BUTTON_1      =  0,
	MOUSE_BUTTON_2      =  1,
	MOUSE_BUTTON_3      =  2,
	MOUSE_BUTTON_4      =  3,
	MOUSE_BUTTON_5      =  4,
	MOUSE_BUTTON_6      =  5,
	MOUSE_BUTTON_7      =  6,
	MOUSE_BUTTON_8      =  7,
	MOUSE_BUTTON_LAST   = MOUSE_BUTTON_8,
	MOUSE_BUTTON_LEFT   = MOUSE_BUTTON_1,
	MOUSE_BUTTON_RIGHT  = MOUSE_BUTTON_2,
	MOUSE_BUTTON_MIDDLE = MOUSE_BUTTON_3
};